In [3]:
import tensorflow as tf

In [ ]:
# scalar - single value shape will be 0

scalar = tf.constant(2, dtype=float)

print(scalar)

tf.Tensor(2.0, shape=(), dtype=float32)


In [ ]:
# vector - list of values one dimension only have shape no range
vector = tf.constant([1, 2, 3, 4])
print(vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [11]:
# matrix - 2 dimension 
matrix = tf.constant([
    [1, 2, 3, 4], 
    [4, 3, 2, 1]])
print(matrix)

tf.Tensor(
[[1 2 3 4]
 [4 3 2 1]], shape=(2, 4), dtype=int32)


In [7]:
# tensor - 3 dimension row, column & range(direction)
# below exmaple 
# block - 2 
# row - 3
# colum - 2
# shape of the tensor is 2, 3, 2
tensor = tf.constant([
    [
        [1, 2],
        [3, 4],
        [4, 5]
    ],
    [
        [5, 6],
        [7, 8],
        [8, 9]
    ]
])
print(tensor)

tf.Tensor(
[[[1 2]
  [3 4]
  [4 5]]

 [[5 6]
  [7 8]
  [8 9]]], shape=(2, 3, 2), dtype=int32)


In [12]:
import numpy as np

In [10]:
# convert tensor to numpy vice versa

new_tensor = tf.constant([
    [
        [
            [1, 2]
        ]
    ],
    [
        [
            [1, 2]
        ]
    ],
    [
        [
            [1, 2]
        ]
    ]
])

print(new_tensor.numpy())



[[[[1 2]]]


 [[[1 2]]]


 [[[1 2]]]]


In [14]:
# convert numpy to tensor 
num_list = np.array([1, 2, 4, 5])
print(num_list)
print(tf.constant(num_list))

[1 2 4 5]
tf.Tensor([1 2 4 5], shape=(4,), dtype=int64)
