In [1]:
import tensorflow as tf

In [ ]:
# create new tensor

new_tensor = tf.constant(
[
    [
        [
            1000, 1001, 1002, 1003
        ],
        [
            2000, 2001, 2002, 2003
        ]
    ],
     [
        [
            4000, 4001, 4002, 4003
        ],
        [
            5000, 5001, 5002, 5003
        ]
    ],
     [
        [
            6000, 6001, 6002, 6003
        ],
        [
            7000, 7001, 7002, 7003
        ]
    ],
     [
        [
            8000, 8001, 8002, 8003
        ],
        [
            9000, 9001, 9002, 9003
        ]
    ]
])
new_tensor.shape    

TensorShape([4, 2, 4])

In [19]:
new_tensor[1, 1, 1] 

<tf.Tensor: shape=(), dtype=int32, numpy=5001>

In [26]:
# spilt features and answers
features = new_tensor[ :, :, 0:3]
answers = new_tensor[:, :, 3:]
print(features.numpy())
print(answers.numpy())

[[[1000 1001 1002]
  [2000 2001 2002]]

 [[4000 4001 4002]
  [5000 5001 5002]]

 [[6000 6001 6002]
  [7000 7001 7002]]

 [[8000 8001 8002]
  [9000 9001 9002]]]
[[[1003]
  [2003]]

 [[4003]
  [5003]]

 [[6003]
  [7003]]

 [[8003]
  [9003]]]


In [28]:
import numpy as np

In [43]:
list = np.arange(1, 10, dtype=int).reshape(-1, 1)
mul_list = list * 2
print(list)
print(mul_list)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]]
